"""create guide_assignments table

Revision ID: 5b2862bf5748
Revises: b7f4687e3614
Create Date: 2026-08-27 14:33:06.542341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2862bf5748'
down_revision: Union[str, Sequence[str], None] = 'b7f4687e3614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guide_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('departure_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['departure_id'], ['departures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guide_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_id', 'departure_id', name='uix_guide_departure')
    )
    op.create_index(op.f('ix_guide_assignments_departure_id'), 'guide_assignments', ['departure_id'], unique=False)
    op.create_index(op.f('ix_guide_assignments_guide_id'), 'guide_assignments', ['guide_id'], unique=False)
    op.create_index(op.f('ix_guide_assignments_id'), 'guide_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guide_assignments_id'), table_name='guide_assignments')
    op.drop_index(op.f('ix_guide_assignments_guide_id'), table_name='guide_assignments')
    op.drop_index(op.f('ix_guide_assignments_departure_id'), table_name='guide_assignments')
    op.drop_table('guide_assignments')
    # ### end Alembic commands ###
