"""create destinations table

Revision ID: a037cebf9e01
Revises: e8d41a948b15
Create Date: 2026-08-26 18:52:25.896053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a037cebf9e01'
down_revision: Union[str, Sequence[str], None] = 'e8d41a948b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_public_id'), 'categories', ['public_id'], unique=True)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_id'), 'destinations', ['id'], unique=False)
    op.create_index(op.f('ix_destinations_public_id'), 'destinations', ['public_id'], unique=True)
    op.create_index(op.f('ix_destinations_slug'), 'destinations', ['slug'], unique=True)
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('base_price_adult', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_price_child', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('base_price_infant', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('duration_nights', sa.Integer(), nullable=False),
    sa.Column('inclusions', sa.JSON(), nullable=True),
    sa.Column('exclusions', sa.JSON(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('gallery_image_urls', sa.JSON(), nullable=True),
    sa.Column('min_group_size', sa.Integer(), nullable=False),
    sa.Column('max_group_size', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tours_category_id'), 'tours', ['category_id'], unique=False)
    op.create_index(op.f('ix_tours_destination_id'), 'tours', ['destination_id'], unique=False)
    op.create_index(op.f('ix_tours_id'), 'tours', ['id'], unique=False)
    op.create_index(op.f('ix_tours_public_id'), 'tours', ['public_id'], unique=True)
    op.create_index(op.f('ix_tours_slug'), 'tours', ['slug'], unique=True)
    op.create_table('departures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=10), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('slots_booked', sa.Integer(), nullable=False),
    sa.Column('price_override_adult', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_override_child', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('open', 'full', 'cancelled', 'completed', name='departure_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departures_id'), 'departures', ['id'], unique=False)
    op.create_index(op.f('ix_departures_public_id'), 'departures', ['public_id'], unique=True)
    op.create_index(op.f('ix_departures_status'), 'departures', ['status'], unique=False)
    op.create_index(op.f('ix_departures_tour_id'), 'departures', ['tour_id'], unique=False)
    op.create_table('tour_itinerary_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('meals_included', sa.String(), nullable=True),
    sa.Column('accommodation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tour_id', 'day_number', name='uix_tour_day_number')
    )
    op.create_index(op.f('ix_tour_itinerary_days_id'), 'tour_itinerary_days', ['id'], unique=False)
    op.create_index(op.f('ix_tour_itinerary_days_tour_id'), 'tour_itinerary_days', ['tour_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_itinerary_days_tour_id'), table_name='tour_itinerary_days')
    op.drop_index(op.f('ix_tour_itinerary_days_id'), table_name='tour_itinerary_days')
    op.drop_table('tour_itinerary_days')
    op.drop_index(op.f('ix_departures_tour_id'), table_name='departures')
    op.drop_index(op.f('ix_departures_status'), table_name='departures')
    op.drop_index(op.f('ix_departures_public_id'), table_name='departures')
    op.drop_index(op.f('ix_departures_id'), table_name='departures')
    op.drop_table('departures')
    op.drop_index(op.f('ix_tours_slug'), table_name='tours')
    op.drop_index(op.f('ix_tours_public_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_destination_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_category_id'), table_name='tours')
    op.drop_table('tours')
    op.drop_index(op.f('ix_destinations_slug'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_public_id'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_id'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_public_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
