"""add actual_start_at and actual_end_at to departures

Revision ID: b4994ef3daec
Revises: 02c7f6c08907
Create Date: 2026-08-28 14:59:27.767172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4994ef3daec'
down_revision: Union[str, Sequence[str], None] = '02c7f6c08907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_travelers', sa.Column('public_id', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_booking_travelers_public_id'), 'booking_travelers', ['public_id'], unique=True)
    op.add_column('departures', sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('departures', sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departures', 'actual_end_at')
    op.drop_column('departures', 'actual_start_at')
    op.drop_index(op.f('ix_booking_travelers_public_id'), table_name='booking_travelers')
    op.drop_column('booking_travelers', 'public_id')
    # ### end Alembic commands ###
