"""create attendances table

Revision ID: da189de5e6be
Revises: 846b03713d31
Create Date: 2026-08-28 15:25:33.871058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da189de5e6be'
down_revision: Union[str, Sequence[str], None] = '846b03713d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_id', sa.Integer(), nullable=False),
    sa.Column('booking_traveler_id', sa.Integer(), nullable=False),
    sa.Column('marked_by_guide_id', sa.Integer(), nullable=True),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_traveler_id'], ['booking_travelers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['departure_id'], ['departures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by_guide_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departure_id', 'booking_traveler_id', name='uix_attendance_traveler')
    )
    op.create_index(op.f('ix_attendances_booking_traveler_id'), 'attendances', ['booking_traveler_id'], unique=False)
    op.create_index(op.f('ix_attendances_departure_id'), 'attendances', ['departure_id'], unique=False)
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.alter_column('booking_travelers', 'public_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking_travelers', 'public_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_departure_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_booking_traveler_id'), table_name='attendances')
    op.drop_table('attendances')
    # ### end Alembic commands ###
